### ISSUE TITLE
defense fields just dont cut it, command vettes are insane

### ISSUE THREAD

**Issue by Novaras** [HW-PlayersPatch/2.3#42] opened 2018-06-17 08:25 UTC
DFFs just don't hold up. Lets avoid citing best-case idyllic scenarios for this unit. Yes, it can block upwards of 70% of incoming fire when stacked. Yes, this can make for some serious damage nullification, however in all honesty this unit is *insanely worse* than command corvettes, its even worse than the upcoming def. fighters from Taii, hell, its even worse than support frigates.

Late game Vgr vs Hgn is just a depressing affair with equally skilled opponents... at a high level there are a slew of issues which are mostly addressed by existing changes however this difference between specialist units is just too much.

Vaygr already have superior lategame production.
Vaygr already have superior unmicro'd swarm.
Vaygr already have superior micro'd swarm (vay emp is objectively better, even if Hgn can hit vettes a little better its hardly providing the same value at all, especially considering how much vettes split up compared to fighters)
Vaygr already have superior unmicro'd frigates.

I could go on like this, and obviously there are areas where Hgn excel where Vgr struggle, but this is one difference which is unjustifiably huge.

Command vettes provide a staggering 7% buff to both accuracy *and* damage for all ships in radius... for **400 rus!?** Not only that, but this buff is *passive*, meaning Vgr hardly has to care at all aside from maybe shuffling its guard target now and then.

Partly because Vgr have so much production, but also partly because its build time is a tiny 30s, command vettes are honestly borderline expendable, and losing one or both is not much of a blow.

To summarise this unit:
* low ru cost
* low time cost
* **low apm cost**
* low risk
* very high reward

In contrast, defense field tech is *1500!*, and each frigate costs *1250!*, with a *70s!* build time, which is even *worse* considering Hgn don't have queues to spare, of all the races. What's worse, this unit is actually nothing without a ton of babysit and attention investment... only to be sniped by all the following:

- bombers
- heavy vettes
- pulsars
- lasers
- battlecruisers

And to top it off, unless you stack the fields two-at-once, even concentrated fire from frigates takes this thing down before its ability timer is even up. 

* high ru cost
* high time cost
* high apm cost
* high risk
* high reward... assuming your opponent doesn't just pull back and stall the timer...

I don't claim to know the best way to buff this unit. For my money, I'd up the speed by `40ms`, give it an extra `1000HP`, lower the build time by `10s` and the tech price by `250`, and finally I'd bump the shield radius from `1200m` to `1400m`. All of this together is almost certainly an overbuff, and is just to get the ball rolling. There are plenty of other approaches, such a regeneration or even shaving a few seconds off the recharge.

Just to clarify this now: I *sincerely* don't care what this unit's stats were in classic. This is not classic. People playing 2.3 for single player fixes won't notice a single change we make here. The people paying attention to these changes don't want to play classic, they want to play a balanced game.

**Comment by Echo1707** [comment] 2018-06-17 11:37
What about a nerf to command corvettes too/instead? 1) that unit does too much for its cost and 2) the more ships there are around it, the greater its effect (late game better production means more ships to be buffed by the command corvette).
For example, if the accuracy buff is removed, we know that ships inside the radius will have 7% more dps flat. If the damage buff is removed, we would have to calculate how much that translated for dps, but we will be sure (barring some mechanics I'm not aware of) that at least HMFs won't be affected.
Research cost, build time and build cost might go up to make the command corvette not that expendable anymore.

If a race has better production, it should have worse units, not better ones. Unless there is a way to balance it via activable abilities used by hiigarans.

**Comment by Novaras** [comment] 2018-06-17 14:55
command vettes:
price: `400 => 800 (+100%)`
time: `30 => 40 (+33%)`
effect radius: `4500 => 2000 (-55%)`

**Comment by Novaras** [comment] 2018-06-17 15:35
do it here

**Comment by cloaked2222** [comment] 2018-06-20 04:54
That's a lot in one post. Here's some thoughts, starting with the title.

DFF vs Command Corvs is not a comparison I would make.

Command vettes are cheap/mobile/fragile FCTs. Their weakness is they are very easy to kill. In a swarm fight, those are the first things you target down.

As hiig you want 1500ru FCTs on your cruisers at all times, and you then recycle them for 1200ru when your cruisers go down. Net cost is 300 each. You can put them on forward forward MS or CCs to the same effect and they will usually last the whole game. FCTs also don't eat into your production cues at all.

Cmd vettes and FCTs both accomplish the same 7% accuracy and DPS boost, which is capped at 20%. Unit cap on cmd vettes is 2 though, so as vay you'll need at-least once FCT to get the full effect.

Funny enough, we actually buffed cmd vettes for v2.0 in health and movement script over hw2c. That's right BUFFED. In hw2c/HWR v1.3 they were such easy targets, that the 30 seconds of build time they occupied often wasn't worth it in a swarm fight. They were best used defensively to guard BCs and the like from range. And this is for a unit that at the time gave a 15% accuracy and DPS boost, which was capped at 40%, and had a unit cap of 3... The major down side back then was 3 of these took up 25% of the 12 squadron unit cap though, which was a big negative.

Cmd vette range reduction is totally cool. Keep price at 400 (minelayers are going to 400), and set build time to 45 (minelayers are at 45).

DFF is a great ship mid to late game top level 1v1. It forces your opponent to attack into you, rather than engage at the desired max range fight. The amount of DPS 2 of these in tandem can absorb is simply sick, even vs cruisers. 17 Ions + 2 DFF vs 21 HMF is balanced to be a draw when DFF are targeted down first. Have you seen even seen cloaked DFF's before? :)

DFF 2.0 Changes:
Cost 1250->1000
Build Speed 70->60 seconds
Duration 20->32 seconds (this is what was most needed over hw2c)
2.3 b1 Changes:
Cost 1000->1250 (to match hw2c)
Build Time 60->70 (to match hw2c)

Don't want to keep changing cost/build time around. I'm ok with a significant DFF health buff, do 20,00->25,900 (30%) to match an upgraded ion cannon frigate. This should be fine. Turn speed can also be buffed. Top speed shouldn't go up, or its going to start evading HMF missiles...

Regarding your broader Hiig/Vaygr concerns:
If I were to make a sc2 comparison, vaygr is like zerg exercising map control, while hiig is like protoss working best in a big ball. Like starcraft, map size has a lot to do with race balance. Lets take fallen-lords for example, i'd roughly say:
Close spawn: favor hiig to a degree
Middle spawn: balanced
Far spawn: favor vay to a degree

Spend some time and really compare the research and subsystems for each race, not just the ships. You may notice things you haven't before, as there's quite a bit of flavor. Hiig has much cheaper DD's for example, everything from cap fac costs, research costs, and upgrade costs. This alone can knock vaygr out of the mid-game.

Whoever balanced hw2c did a fantastic job imho. Overall game balance in the hw2c 1.1 patch was great from 2003 to 2015. Hiig/Vaygr in HWR were also nearly identical to hw2c from v1.0 to v1.3 (other than some gearbox bugs/changes). The biggest two race balance issues were not by design:
1. Vaygr harvesting was 5-10% worse
-Stats were the same, but the Vaygr MS is just shit at accepting RU.
-This made it impossible for vaygr to beat hiig on small maps
2. Vaygr BC had a huge range advantage
-BC range stats were the same, but the trinity cannon was located on the nose of the vaygr BC, while the ion turrets were set back on the hiig BC.
-This gave Vaygr a huge advantage on large maps, once cruisers were in play

Yes hw2c also had some UP units, for example:
-Hiig EMP (can be dodged by fighters)
-Gunships (did not perform well)
-Vay Lance (debatable, but did not perform that great)
-Vay Assault Frigs (had weapon bugs as i recall, was maybe half as good as a flak frig)
-Hyperspace Gates (expensive/time consuming)
OP units were mainly cruisers on large maps.

If vaygr feels OP atm, its likely due to the much much cheaper upgrades in HWR, which used to be huge cost barriers for vaygr in hw2c. Rather than try to re-paint the MonaLisa and remove vaygr's flavor/advantages, the best way to tame vaygr is to simply reduce their harvesting slightly:
-Starting colls can stay at 7 to overcome the shit vay MS (was 6 in hw2c)
-Collector RU capacity can drop from 2.1's 208ru to 200ru, a 4% drop (was 200ru in hw2c)
I already made this large update on 6/1 per our vaygr discussion, which i'm sure you forgot. =P

hw2c unit caps: Hiig 4ccs, Vay 6ccs (Vay is limited to one build facility per CC, this is a serious limitation)
HWR 2.1: Hiig 3ccs, Vay 4ccs, Hw1 3ccs
To address production concerns, all races can also get one more carrier on normal/large/huge (vast is 2x huge i think)
-Be sure to increase the total for capital ships by one too.
-hw1 is currently capped at 3 cc's on High/Huge too, so it should go to 5 to match the new hiig.
-Be sure to check ALL the unit cap locations (search 2.205), Gearbox's new unit caps file structure is a friken mess.

**Comment by Novaras** [comment] 2018-06-20 11:39
FCT and cmd vette are **not** comparable, that's completely unfair.
* you don't attain this 'net cost' until you sell the module, until then you are down 1200RU and after you're likely down the cruiser you build it on
* this 1200RU is spent on a worse command vette, as the mobility is the mobility of a cruiser
* they take 10s longer to build (minor, whatever, offset by using a subsystem queue)
* fire control doesn't affect the host ship - sinking 3k into double fire control on hgn cruisers against vay who has to spend 300 ru for the **same effect** since all four cruisers in this scenario are covered by one fire control field

I'm fine with just the nerfs we agree on so far, but don't try to make that comparison again please, its not fair and completely untrue. I'm not the best player of all time, and I'm sure plenty of better players would agree with you on your points, but I just don't see it.

Hgn is *not* protoss, vgr is *not* zerg. Hgn is probably terran at a stretch, whereas vgr is both protoss and zerg combined into one. Vgr have the *best* deathball, they have the strongest lategame, their earlygame is no weakness, they always have more map control, they always have more production, and while their module switching is definitely a downside, in v7 it really doesn't matter because they are *guaranteed* to have imp. manufacturing, they are likely to splurge out max cap on a unit class then switch before you've even dented their cloud. But its not even just that, because they don't *need* to engage you, vgr is very happy to sit back and watch you panic as you realise you already cant engage, and your matchup is just going to get worse.

I simply can't abide this philosophy of 'hgn better early', 'vgr better late' that gets thrown around. All races should have options in all stages of the game. In a max-vs-max brawl, def fields will certainly have the potential to push the HMFs off a cruiser in order to snipe it, but it really doesn't matter at all, because you just lost the swarm fight because 'vaygr is supposed to be the swarm race'???!!?? To top it off your dffs are about to time out and now your ions have to fight HMFs which were **already superior** to begin with, and now they have a fucking 14% damage boost????? what the fuck???

I can't scope out how this matchup will look like in v8, maybe it will be fine. So I'm not complaining about the changes we've already made and they may in fact be enough. But right now, as it is, and in all prior versions of RM I've played, vgr is truly top dog. If this game had a larger scene, hell, even with 100 or more players, the top guys would absolutely spam vaygr all day.

DFF price hike is fine, they are a power unit. This build time is what gets me. 70s is just stunningly long, what game am I playing where I can spend 70s (54s) on a unit which will survive for exactly one (or less) activations before getting sniped? There are *plenty* of scenarios where the opponent, in whatever race, can simply kite away the activation time... and the DFF can't even press the issue since its slower than all frigates! Not only that, but the nature of snowballing means that if I *dare* to spend 54s on two queues for a unit which can be kited out, my opponent will have *four* more ions/hmfs than me, and in the interim they'll have a +2 advantage. Yes, this sounds like nothing since a DFF is worth more than a single HMF, no debate there. However this interim time where I'm down on frigate count, I'm getting snowballed. HMFs don't actually even need a numbers advantage to do this to ions. Let's also throw in some cmd vettes and my production downtime is just *wow*.

**17 ions + 2DFF should be a *stomp* for the ions.** This is brainless and sloppy play for vaygr, they should get smashed if they take a fight like that. Yes, I've used cloaked DFFs, yes it will beat an unskilled vaygr, or anyone for that matter. But anyone with any sense at all will just kite away until they get a few proxys out. Why are we balancing units around opponent stupidity instead of actual effectiveness. No, I'm not saying human factor should be disregarded, but this is too much. 

The reason I compared DFF with cmd vette was that these are both unique support units for the HW2 races, which they can use to alter the power of their existing units. My point is that cmd vettes are throwaway, whereas DFFs are so expensive it hurts. The micro difference between them is so laughably huge it hurts too. Hgn has to work *so hard* to get their support unit working, vaygr just throws theirs out there and gets passive bonuses. Whatever.

DFF:
HP up: `20000 => 25000`
Shield radius up: `1200 => 1300`

Cmd vette:
Fire control radius down: `4200 => 2100`
Build time up: `30 => 45`

**Comment by cloaked2222** [comment] 2018-06-21 23:19
Fear: "if ur gonna chop cmd vette radius they need to circle closer to compensate especially in evasive those things fly waaaay off"

**Comment by cloaked2222** [comment] 2018-07-08 19:15
Implemented:

DFF
HP: 20k->25k
rotationMaxSpeed: 22->35
rotationAccelTime: .75->.4
rotationBrakeTime: .4->.2
Didn't increase the shield range, as that also makes it easier to get inside the shield and snipe them with frigs. Above changes should significantly increase survivability.

Marine Frigate
HP: 20k->25k To match DFF health buff, as neither of these ships can be upgraded. Marines are also a bit UP. Vay infiltrators start at 20k and are 28k when upgraded.

Cmd vette
Build time: 30->45
Effect radius: 4500->2200
GuardCommand fGuardRadius: 3000->1000 http://hw2wiki.net/wiki.hw2.info/FunctionaddAbility_show_comments=1.html
flyround_commandvette.lua
distanceFromTarget 1600->1000
distanceFromTargetAg 1600->1000
distanceFromTargetEv 2000->1400
Ran some in game and this looks good. Did 2cmd + 40missiles vs 44missiles.

Max FCT stack:
WeaponDamage = 1.2->1.15
WeaponAccuracy = 1.2->1.15

https://github.com/HW-PlayersPatch/2.3/commit/b0319948c7f251511ec203232f731552a0051cf3
Closing this, but feel free to re-open if needed.

**Closed by cloaked2222** 2018-07-08 19:15 UTC
Labels: discussion
